dateModified: 1748896333
email:
  fromEmail: rodrigopassos@mac.com
  fromName: 'Craft Copilot'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    36bf75f8-4532-448b-90e9-70a328a9d23c: 'Craft Copilot' # Craft Copilot
    75c5b275-90a5-4097-a01f-ad7632742dca: 'Craft Copilot' # Craft Copilot
system:
  edition: solo
  live: true
  name: 'Craft Copilot'
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
